import { useState } from 'react';
import { Download, FileText, Receipt, Upload, X, CheckCircle2, Clock3 } from 'lucide-react';

const payroll = [
  { month: 'September 2026', gross: '$128,450.00', taxes: '$31,612.50', net: '$96,837.50', status: 'Processing' },
  { month: 'August 2026', gross: '$126,880.00', taxes: '$31,112.00', net: '$95,768.00', status: 'Paid' },
  { month: 'July 2026', gross: '$125,200.00', taxes: '$30,670.00', net: '$94,530.00', status: 'Paid' },
  { month: 'June 2026', gross: '$123,950.00', taxes: '$30,267.50', net: '$93,682.50', status: 'Paid' },
];

function PayslipModal({ onClose }: { onClose: () => void }) {
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4" role="dialog" aria-modal="true" aria-labelledby="payslip-title">
    <div className="w-full max-w-2xl rounded-2xl bg-white shadow-2xl animate-scale-in">
      <div className="flex items-center justify-between border-b border-slate-100 px-6 py-4"><div><h2 id="payslip-title" className="font-bold text-slate-900">September 2026 Payslip</h2><p className="text-xs text-slate-500">NexusHR · Payroll statement</p></div><button onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100" aria-label="Close"><X className="h-5 w-5" /></button></div>
      <div className="p-6"><div className="mb-6 flex items-start justify-between"><div><p className="text-sm font-semibold text-slate-900">Sarah Chen</p><p className="text-xs text-slate-500">Chief People Officer · EMP-1042</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700">Paid</span></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Gross pay','$8,920.00'],['Taxes','$2,210.40'],['Benefits','$340.00'],['Net pay','$6,369.60']].map(([label,value])=><div key={label} className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-bold text-slate-900">{value}</p></div>)}</div><div className="mt-6 border-t border-slate-100 pt-4 text-xs text-slate-500"><div className="flex justify-between py-1"><span>Pay period</span><span className="font-medium text-slate-700">Sep 1 – Sep 30, 2026</span></div><div className="flex justify-between py-1"><span>Payment date</span><span className="font-medium text-slate-700">Sep 30, 2026</span></div></div></div>
      <div className="flex justify-end gap-2 border-t border-slate-100 px-6 py-4"><button onClick={() => window.print()} className="flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-700"><Download className="h-4 w-4" />Print / Save PDF</button></div>
    </div>
  </div>;
}

export function Payroll() {
  const [showPayslip, setShowPayslip] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  return <div className="space-y-6 p-4 lg:p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-widest text-blue-600">Finance & wellbeing</p><h2 className="mt-1 text-2xl font-bold tracking-tight text-slate-900">Payroll & Expenses</h2><p className="mt-1 text-sm text-slate-500">Keep pay runs, payslips, and employee expenses in one place.</p></div><button onClick={() => setShowPayslip(true)} className="flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-blue-600/20 hover:bg-blue-700"><FileText className="h-4 w-4" />Download payslip</button></div>
    <div className="grid gap-4 sm:grid-cols-3">{[['Total payroll','$128,450','September run'],['Net disbursement','$96,837.50','After deductions'],['Pending expenses','$4,280.75','12 submissions']].map(([label,value,detail],i)=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className={`mb-4 flex size-10 items-center justify-center rounded-xl ${i===0?'bg-blue-50 text-blue-600':i===1?'bg-emerald-50 text-emerald-600':'bg-amber-50 text-amber-600'}`}><Receipt className="h-5 w-5" /></div><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-slate-900">{value}</p><p className="mt-1 text-xs text-slate-400">{detail}</p></div>)}</div>
    <div className="grid gap-6 xl:grid-cols-[1.5fr_1fr]"><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h3 className="font-bold text-slate-900">Payroll summary</h3><p className="text-xs text-slate-500">Monthly payroll breakdown</p></div><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-700">FY 2026</span></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-400"><tr><th className="px-5 py-3 font-semibold">Pay period</th><th className="px-5 py-3 font-semibold">Gross pay</th><th className="px-5 py-3 font-semibold">Taxes</th><th className="px-5 py-3 font-semibold">Net pay</th><th className="px-5 py-3 font-semibold">Status</th></tr></thead><tbody>{payroll.map((row)=><tr key={row.month} className="border-t border-slate-100"><td className="whitespace-nowrap px-5 py-4 font-semibold text-slate-700">{row.month}</td><td className="px-5 py-4 text-slate-600">{row.gross}</td><td className="px-5 py-4 text-slate-600">{row.taxes}</td><td className="px-5 py-4 font-semibold text-slate-900">{row.net}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${row.status==='Paid'?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{row.status}</span></td></tr>)}</tbody></table></div></section>
      <div className="space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-3"><div className="rounded-xl bg-violet-50 p-2.5 text-violet-600"><Upload className="h-5 w-5" /></div><div><h3 className="font-bold text-slate-900">Submit an expense</h3><p className="text-xs text-slate-500">Reimbursements are reviewed within 3 days</p></div></div>{submitted?<div className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800"><div className="flex items-center gap-2 font-semibold"><CheckCircle2 className="h-4 w-4" />Expense submitted</div><p className="mt-1 text-xs">Your $0.00 draft is now pending review.</p></div>:<form onSubmit={(e)=>{e.preventDefault();setSubmitted(true)}} className="flex flex-col gap-3"><input required placeholder="Expense description" className="rounded-lg border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-blue-500" /><div className="grid grid-cols-2 gap-3"><input required type="number" min="0" step="0.01" placeholder="Amount" className="rounded-lg border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-blue-500" /><select className="rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-600"><option>Travel</option><option>Meals</option><option>Equipment</option></select></div><button className="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white hover:bg-slate-800">Submit expense</button></form>}</section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><h3 className="font-bold text-slate-900">Receipt tracking</h3><span className="text-xs font-semibold text-blue-600">View all</span></div><div className="flex flex-col gap-3">{[['Team offsite dinner','$680.00','In review'],['Airport transfer','$84.50','Approved'],['Office supplies','$126.25','Needs receipt']].map(([name,amount,status])=><div key={name} className="flex items-center gap-3"><div className="rounded-lg bg-slate-100 p-2 text-slate-500">{status==='Approved'?<CheckCircle2 className="h-4 w-4 text-emerald-600"/>:<Clock3 className="h-4 w-4"/>}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-slate-700">{name}</p><p className="text-xs text-slate-400">{status}</p></div><p className="text-sm font-semibold text-slate-700">{amount}</p></div>)}</div></section></div></div>{showPayslip&&<PayslipModal onClose={()=>setShowPayslip(false)} />}</div>;
}

export default Payroll;
