import { useState } from 'react';
import { MessageSquare, Target, Users, X, CheckCircle2 } from 'lucide-react';

const goalColors: Record<string, string> = { blue: 'bg-blue-500', violet: 'bg-violet-500', emerald: 'bg-emerald-500', amber: 'bg-amber-500' };

const initialGoals = [
  { title: 'Improve onboarding experience', owner: 'People Operations', progress: 72, due: 'Due Oct 15', color: 'blue' },
  { title: 'Launch manager enablement series', owner: 'Learning & Development', progress: 48, due: 'Due Nov 01', color: 'violet' },
  { title: 'Reduce time-to-hire by 15%', owner: 'Talent Acquisition', progress: 86, due: 'Due Sep 30', color: 'emerald' },
  { title: 'Build inclusive leadership toolkit', owner: 'Culture Committee', progress: 33, due: 'Due Dec 12', color: 'amber' },
];

export function Performance() {
  const [goals, setGoals] = useState(initialGoals);
  const [reviewOpen, setReviewOpen] = useState(false);
  const [sent, setSent] = useState(false);
  return <div className="space-y-6 p-4 lg:p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-widest text-violet-600">Growth & alignment</p><h2 className="mt-1 text-2xl font-bold tracking-tight text-slate-900">Performance & OKRs</h2><p className="mt-1 text-sm text-slate-500">Align team goals, celebrate progress, and make feedback continuous.</p></div><button onClick={()=>setReviewOpen(true)} className="flex items-center justify-center gap-2 rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-violet-600/20 hover:bg-violet-700"><MessageSquare className="h-4 w-4" />Request 360° feedback</button></div>
    <div className="grid gap-4 sm:grid-cols-3">{[['Company progress','61%','Across 18 active OKRs'],['Reviews completed','24 of 32','Q3 review cycle'],['Feedback received','8 notes','This quarter']].map(([label,value,detail],i)=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><p className="text-sm text-slate-500">{label}</p><div className={`rounded-lg p-2 ${i===0?'bg-blue-50 text-blue-600':i===1?'bg-emerald-50 text-emerald-600':'bg-violet-50 text-violet-600'}`}>{i===0?<Target className="h-4 w-4"/>:i===1?<CheckCircle2 className="h-4 w-4"/>:<Users className="h-4 w-4"/>}</div></div><p className="mt-3 text-2xl font-bold text-slate-900">{value}</p><p className="mt-1 text-xs text-slate-400">{detail}</p></div>)}</div>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-5 flex items-center justify-between"><div><h3 className="font-bold text-slate-900">Team goals & OKRs</h3><p className="text-xs text-slate-500">Adjust progress as work moves forward</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">Q3 · 4 goals</span></div><div className="grid gap-4 md:grid-cols-2">{goals.map((goal,index)=><div key={goal.title} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><div className="mb-2 flex items-center gap-2"><span className={`size-2 rounded-full ${goalColors[goal.color]}`} /><h4 className="font-semibold text-slate-800">{goal.title}</h4></div><p className="text-xs text-slate-500">{goal.owner} · {goal.due}</p></div><span className="text-lg font-bold text-slate-900">{goal.progress}%</span></div><input aria-label={`Progress for ${goal.title}`} type="range" min="0" max="100" value={goal.progress} onChange={(e)=>setGoals(goals.map((g,i)=>i===index?{...g,progress:Number(e.target.value)}:g))} className="mt-5 w-full accent-violet-600" /><div className="mt-2 flex justify-between text-[11px] font-medium text-slate-400"><span>Not started</span><span>On track</span><span>Complete</span></div></div>)}</div></section>
    {reviewOpen&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4" role="dialog" aria-modal="true" aria-labelledby="review-title"><div className="w-full max-w-lg rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-4"><div><h2 id="review-title" className="font-bold text-slate-900">Request 360° feedback</h2><p className="text-xs text-slate-500">Invite a colleague to share a perspective</p></div><button onClick={()=>setReviewOpen(false)} aria-label="Close" className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X className="h-5 w-5"/></button></div>{sent?<div className="p-8 text-center"><CheckCircle2 className="mx-auto h-10 w-10 text-emerald-500"/><h3 className="mt-3 font-bold text-slate-900">Request sent</h3><p className="mt-1 text-sm text-slate-500">Your colleague will receive an email shortly.</p></div>:<form onSubmit={(e)=>{e.preventDefault();setSent(true)}} className="flex flex-col gap-4 p-6"><label className="flex flex-col gap-1.5 text-sm font-medium text-slate-700">Colleague email<input required type="email" placeholder="name@nexushr.com" className="rounded-lg border border-slate-200 px-3 py-2.5 font-normal outline-none focus:border-violet-500"/></label><label className="flex flex-col gap-1.5 text-sm font-medium text-slate-700">What would you like feedback on?<textarea required rows={4} placeholder="Share a focus area or context…" className="rounded-lg border border-slate-200 px-3 py-2.5 font-normal outline-none focus:border-violet-500"/></label><button className="rounded-lg bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-violet-700">Send request</button></form>}</div></div>}
  </div>;
}
export default Performance;
